### ISSUE TITLE
Random SIGSEGV

### ISSUE THREAD

**Issue by sotally-tober** [technically-functional/heartbeat#14]
This is most likely user error, since I'm not very familiar with Docker.

I cloned the repo, ran `HB_PATH=$HOME/heartbeat/config docker compose up --build`. This didn't work because for some reason there's no internet access within the compose build thing, so I had to add `network: "host"` to `services.server.build` in `docker-compose.yml`.

After this, it built successfully, but the moment I did `curl localhost:6060` it panicked with this:

```
heartbeat-server-1    | panic: runtime error: invalid memory address or nil pointer dereference
heartbeat-server-1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76e082]
heartbeat-server-1    | 
heartbeat-server-1    | goroutine 13 [running]:
heartbeat-server-1    | main.RequestHandler(0xc0000ad080)
heartbeat-server-1    |         /heartbeat/handlers.go:35 +0x1e2
heartbeat-server-1    | github.com/valyala/fasthttp.CompressHandlerLevel.func1(0xc0000ad080)
heartbeat-server-1    |         /go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/server.go:503 +0x3c
heartbeat-server-1    | github.com/valyala/fasthttp.(*Server).serveConn(0xc0000fe200, 0x894e30, 0xc0000100b0, 0x0, 0x0)
heartbeat-server-1    |         /go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/server.go:2266 +0x15ab
heartbeat-server-1    | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000083860, 0xc000050720)
heartbeat-server-1    |         /go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/workerpool.go:223 +0xba
heartbeat-server-1    | github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000083860, 0xc000050720, 0x790ee0, 0xc000050720)
heartbeat-server-1    |         /go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/workerpool.go:195 +0x35
heartbeat-server-1    | created by github.com/valyala/fasthttp.(*workerPool).getCh
heartbeat-server-1    |         /go/pkg/mod/github.com/valyala/fasthttp@v1.30.0/workerpool.go:194 +0x11f
heartbeat-server-1 exited with code 2
```

Any help would be appreciated.

Thanks.

**Comment by l1ving** [comment]
Line 35 in handlers.go (at the time of writing this comment) is `heartbeatStats.totalVisits += 1`

if it panics there, somehow heartbeatStats is nil. The only way for that to happen is if the database to local values loading didn't finish when you curled it?? I'm completely unsure, will take a look in about 3 hours

Will also update the current configs to make more sense

Related: in the time being, can you try while on a network? even in dev (only localhost) I only tried while connected to one

**Comment by l1ving** [comment]
this is the value loading that I'm talking about https://github.com/technically-functional/heartbeat/blob/a619e4e692aa3aa570b26acac3f8b8aae574375a/database.go#L48

**Comment by sotally-tober** [comment]
> Related: in the time being, can you try while on a network? even in dev (only localhost) I only tried while connected to one

I did. I even tried accessing the remote IP through a browser. It gave me the nginx bad gateway page, and on refreshing it 503'd because, well, it panicked.

> The only way for that to happen is if the database to local values loading didn't finish when you curled it??

When I run redis directly on the host instead of using a container, this doesn't happen though. Which is what's odd.
I'm assuming this is some container networking thing on my end, since even `go get`s didn't work without me modifying the docker-compose.yml.

I can also **not** reproduce this when I run locally on my laptop. So Azure/Ubuntu being weird with docker seems the likely candidate.
Still dunno how to fix this though.

**Comment by l1ving** [comment]
> When I run redis directly on the host instead of using a container, this doesn't happen though.

This shouldn't happen regardless, even if it can't connect to nginx it'll default to the default values from the code. 

There was an issue earlier that caused the container to not be able to connect to the database (ran by docker compose)
which mainly fixed
- the address of the redis container in heartbeat's config
- removed host from the network's in the compose file

I will double check if redis is supposed to be accessible from host later 

> I can also not reproduce this when I run locally on my laptop

It's probably something to do with a lack of networks(?). unsure of your setup on either machine

**Comment by sotally-tober** [comment]
> It's probably something to do with a lack of networks(?). unsure of your setup on either machine

Most likely this. I switched VPSes and it works fine now. The first VPS I share with five other people and I'm guessing someone did something weird.

Sorry for the trouble.

**Comment by l1ving** [comment]
Good to hear it was resolved :)

Feel free to re-open this if the issue is reproducable
