### ISSUE TITLE
Enhancement: Live Update of the Counters

### ISSUE THREAD

**Issue by sourTaste000** [technically-functional/heartbeat#21]
Example:

https://user-images.githubusercontent.com/47074495/139297746-36eedd80-a148-4311-bd19-d3c652c4269d.mov

**Comment by d1snin** [comment]
what do you mean by bombing the server, the server, especially on go, works fine, especially with such a load as yours, so you can do it if there is no better solution

**Comment by d1snin** [comment]
You don't think that you want data to be outdated for ~5 seconds for example.

**Comment by l1ving** [comment]
I don't see how a 5 second interval is unreasonable

**Comment by d1snin** [comment]
You can use this, of course, but there's just no difference (absolutely) here

**Comment by d1snin** [comment]
The server will process your request in a couple of tens of milliseconds and will wait, it doesn't matter how many seconds you send the request again

**Comment by d1snin** [comment]
And, well, you will allow the data to be not updated for 5 seconds at most

**Comment by sourTaste000** [comment]
Remove the 'console.log'?

**Comment by l1ving** [comment]
https://github.com/technically-functional/heartbeat/commit/a115d66c24467c299d56652fd135cc2b52287f0c
