### ISSUE TITLE
`total_visits` field is being incremented on each request to `/api/stats`

### ISSUE THREAD

**Issue by d1snin** [technically-functional/heartbeat#27]
This is a bit embarrassing, I would like to expect the immutability of this field, because this is not even the frontend interface of the application, but only an API through which I can get data received from the frontend (if we take into account only `total_visits`)

![totalvisitsbug](https://user-images.githubusercontent.com/68169685/153049824-9b49c2d6-7709-4632-96de-2fd57e088762.gif)

**Comment by d1snin** [comment]
Caused by https://github.com/technically-functional/heartbeat/blob/1ef3b693338e19b433aa0d060abc1a7121df880b/handlers.go#L39

**Comment by sourTaste000** [comment]
I think its caused by discord fetching the embed rather than the client sending a beat to the server

**Comment by d1snin** [comment]
its not related to discord at all

**Comment by d1snin** [comment]
I guess, the problem is caused by:
https://github.com/technically-functional/heartbeat/blob/1ef3b693338e19b433aa0d060abc1a7121df880b/api.go#L45
The `!=` operator should be replaced with `==` :trollface:

**Comment by l1ving** [comment]
This behavior is intentional. If you're using the stats to display your last seen on your GitHub profile, it counts as a visit.

**Comment by l1ving** [comment]
> I guess, the problem is caused by:
> 
> https://github.com/technically-functional/heartbeat/blob/1ef3b693338e19b433aa0d060abc1a7121df880b/api.go#L45
> 
> 
> The `!=` operator should be replaced with `==` (probably :trollface:)

No, the if statement there is to prevent self-api ticking.

**Comment by l1ving** [comment]
Though, I do admit that my choice of the value name was probably not the most clear.

**Comment by d1snin** [comment]
> This behavior is intentional. If you're using the stats to display your last seen on your GitHub profile, it counts as a visit.

Makes sense, but stupid anyway, is it possible to add the query parameter check for it?

```
https://heartbeat.example.com/api/stats?countVisit=true
```

**Comment by l1ving** [comment]
That is quite literally what the current query parameter is for. Sorry that the name was not clear.

**Comment by d1snin** [comment]
Oh, I got it now.
